### ISSUE TITLE
transform_video.py doesn't detect framerate, assumes that every video has FPS 30

### ISSUE THREAD

**Issue by lengstrom** [lengstrom/fast-style-transfer#1]

**Comment by Schwusch** [comment]
This is easily checked beforehand with 
`ffprobe -v quiet -print_format json -show_streams path/video.mp4`
Which returns a json string with all information about the video.

**Comment by Schwusch** [comment]
This is now fixed, but only when using the --no-disk option. Perhaps it should be used by default?

**Comment by AndyZhu1991** [comment]
Maybe it can solve your problem :-)
https://github.com/lengstrom/fast-style-transfer/pull/76
