### ISSUE TITLE
Training not using the GPU?

### ISSUE THREAD

**Issue by mattchiang-gsp** [lengstrom/fast-style-transfer#103]
I've run style.py and trained on images before on my GTX 1080 which ends up taking about 6 hours. For some reason now though, training seems to take over 2 days. I've tried tuning the batch size and training on smaller images, but it still takes forever. The GPU doesn't seem to be used as its temperature stays around 56C and I don't know why.

Any thoughts?

Edit: Other applications seem to be using the GPU just fine. Also tried running sample scripts in [https://www.tensorflow.org/tutorials/using_gpu](https://www.tensorflow.org/tutorials/using_gpu) and Python doesn't seem to be reading the GPU:

`InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'b_1': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/cpu:0 ]. Make sure the device specification refers to a valid device.`

**Comment by walkertraylor** [comment]
I have the same issue.  The other commands have a flag for enabling gpu usage, but this one does not.  Have you been able to get those commands to work using the GPU?

**Comment by lengstrom** [comment]
You're somehow hiding your GPU from the TensorFlow runtime, this is not a problem with my code.
