### ISSUE TITLE
Clarifications about the dataset needed to create a new checkpoint

### ISSUE THREAD

**Issue by arbelotb** [lengstrom/fast-style-transfer#104]
If I understand correctly, the script style.py requires a dataset to train a new network. However I am wondering what type of dataset it requires. 
What should the images look like ? What size should they be ? How many of them do I need ? What dataset where the existing checkpoints trained with ?

Thanks in advance for any information on this topic,

**Comment by msm1089** [comment]
I believe it was trained on the coco2014 dataset for the example checkpoints. I used coco2017 unlabelled (around 120k images). Image size does not matter as the network will scale them to 256x256.

Good luck with your training!

**Comment by arbelotb** [comment]
Thanks for your answer !

Do you know how the dataset relates to the style transfer capabilities ?
For example if I want to use the style transfer on people only, would it be better (or faster) to use people photo only in the dataset ?

**Comment by msm1089** [comment]
Hmm, interesting question. I'm not sure, it may well be, sounds reasonable. You could try using the celebA dataset and comparing results with using coco.

**Comment by arbelotb** [comment]
Ok, I'll try that. Thanks again for the help !
