### ISSUE TITLE
Resume training?

### ISSUE THREAD

**Issue by AnyhowStep** [lengstrom/fast-style-transfer#105]
Let's say, after I run the following,

```
python style.py --style ./custom-model/src.jpg --checkpoint-dir ./custom-model/checkpoint/ --test ./custom-model/test.jpg --test-dir ./custom-model/test --checkpoint-iterations 100 --batch-size 4
```

And, a few hours later, I stop the training. Then, I want to resume from where it left off. How would I do it? From what I've seen it just overwrites the checkpoint files in `./custom-model/checkpoint`, removing hours of work.

**Comment by lengstrom** [comment]
You'll have to restore from the checkpoint. That functionality is missing
right now, pull requests are welcome.
