### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by cdeil** [lengstrom/fast-style-transfer#107]
Hi, I have a question concerning your license:

https://github.com/lengstrom/fast-style-transfer#license

> Copyright (c) 2016 Logan Engstrom. Contact me for commercial use (email: engstrom at my university's domain dot edu). Free for research/noncommercial use, as long as proper attribution is given and this copyright notice is retained.

Does this apply to generated images? I want to make a Christmas gift for personal use, nothing commercial. But if possible, I would prefer not to have any text printed on the image, at least not on the front side. As far as I understand, this is not in line with your copyright / license and I should either put the copyright and attribution or go use other code, right?

**Comment by lengstrom** [comment]
I suppose this is late, but feel free to use stylizations from my network as a non-commercial Christmas gift. :)

**Comment by GinYoshida** [comment]
Hello.

 I'm working in the business department and our customer would like to use the technology for the 1-time exhibition demo for artistic purposes with a small budget.
 We would like to modify the code and use it for the demo if it is OK from the financial point of view. Do you have any criteria for the usage-based sales amount or the company size?

 If you are positive to discuss this topic clearly, e-mail is also welcome.

hitoshi.yoshida@cross-compass.com
