### ISSUE TITLE
ImportError: cannot import name doccer

### ISSUE THREAD

**Issue by Slipin-Abdo** [lengstrom/fast-style-transfer#112]
When I run the command python evaluate.py --checkpoint ./rain-princess.ckpt --in-path <path_to_input_file> --out-path ./output_image.jpg.

I get ImportError: cannot import name doccer

**Comment by zinziroge** [comment]
I don't know about detail, but almost same topic is here.
https://stackoverflow.com/questions/30539950/importerror-cannot-import-name-doccer

So, maybe "scipy" isn't install completely.
You may try uninstall scipy, and install again.

**Comment by limitforever** [comment]
Hello,lengstrom!

I meet the problem:
When I tried "python evaluate.py --checkpoint 

- [ ] path/to/style/la_muse.ckpt"

 ,it occurred that "Process finished with exit code -1073740791 (0xC0000409)"
I don't know why such assertion occurred.
I'll be appreciated if you could answer me.
Thanks a lot.
