### ISSUE TITLE
Train a model

### ISSUE THREAD

**Issue by brainstormapps** [lengstrom/fast-style-transfer#116]
Hi,
I want to train a model using fast-style-transfer
I executed this command
COMMAND
=========
"python style.py --style examples/content/pic1.png --train-path data/bin/train2014 --checkpoint-dir examples/checkpoint --content-weight 1.5e1 --checkpoint-iterations 1000 --batch-size 20"

RESULT
=====
after 12 hours processing there was no model ckpt file.
In checkpoint folder there are four files exist
1. fns.ckpt.meta
2. fns.ckpt.index
3. fns.ckpt.data-00000-of-00001
4.checkpoint

with output on terminal
UID:79
Epoch 0, Iteration: 1000, Loss:1.29471e+07
style: 3.75047e+06, content:8.8546e+06, tv:342004.0

I execute this command without gpu only for test purpose (My Graphic card is gpu supported, I can use it by installing CUDA)
What is wrong with command?
How can I get model file

Thanks and regards
MNA

**Comment by lengstrom** [comment]
Model file doesn't save until the end of training, I believe.

**Comment by Sheyuhao** [comment]
I have similar question.
