### ISSUE TITLE
Three undefined names

### ISSUE THREAD

**Issue by cclauss** [lengstrom/fast-style-transfer#117]
Undefined names may raise NameError at runtime.

flake8 testing of https://github.com/lengstrom/fast-style-transfer on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./evaluate.py:80:21: F821 undefined name 'X'
        img_shape = X[0].shape
                    ^
./style.py:161:38: F821 undefined name 'img'
                save_img(preds_path, img)
                                     ^
./src/utils.py:12:20: F821 undefined name '_get_img'
    style_target = _get_img(style_path, img_size=new_shape)
                   ^
```

**Comment by lengstrom** [comment]
This is probably something wrong with flake8 or the way you are using flake8.
