### ISSUE TITLE
Process finished with exit code -1073740791 (0xC0000409)

### ISSUE THREAD

**Issue by limitforever** [lengstrom/fast-style-transfer#118]
Hello,lengstrom!

I meet the problem:
When I tried "python evaluate.py --checkpoint

    path/to/style/la_muse.ckpt"

,it occurred that "Process finished with exit code -1073740791 (0xC0000409)"
I don't know why such assertion occurred.
I'll be appreciated if you could answer me.
Thanks a lot.

**Comment by limitforever** [comment]
I have solved it !Thank you!

**Comment by Pagey** [comment]
hey LIDA can you tell how you solved it??  Thanks
