### ISSUE TITLE
A training problem

### ISSUE THREAD

**Issue by limitforever** [lengstrom/fast-style-transfer#119]
Hello,lengstrom:
  When I excuted the style.py on my linux server,some problems occured,the following gives the detailed description:
  
 During handling of the above exception, another exception occurred:

PermissionDeniedError                     Traceback (most recent call last)
/home/lemn/exp_data/da/fast-style-transfer-master/style.py in <module>()
    171
    172 if __name__ == '__main__':
--> 173     main()

/home/lemn/exp_data/da/fast-style-transfer-master/style.py in main()
    151     ]
    152
--> 153     for preds, losses, i, epoch in optimize(*args, **kwargs):
    154         style_loss, content_loss, tv_loss, loss = losses
    155

/home/lemn/exp_data/lida/fast-style-transfer-master/src/optimize.py in optimize(content_targets, style_target, content_weight, style_weight, tv_weight, vgg_path, epochs, print_iterations, batch_size, save_path, slow, learning_rate, debug)
    135                     else:
    136                        saver = tf.train.Saver()
--> 137                        res = saver.save(sess, save_path)
    138                     yield(_preds, losses, iterations, epoch)
    139

/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py in save(self, sess, save_path, global_step, latest_filename, meta_graph_suffix, write_meta_graph, write_state)
   1472         model_checkpoint_path = sess.run(
   1473             self.saver_def.save_tensor_name,
-> 1474             {self.saver_def.filename_tensor_name: checkpoint_file})
   1475         model_checkpoint_path = compat.as_str(model_checkpoint_path)
   1476         if write_state:

/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    893     try:
    894       result = self._run(None, fetches, feed_dict, options_ptr,
--> 895                          run_metadata_ptr)
    896       if run_metadata:
    897         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1122     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1123       results = self._do_run(handle, final_targets, final_fetches,
-> 1124                              feed_dict_tensor, options, run_metadata)
   1125     else:
   1126       results = []

/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1319     if handle is None:
   1320       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1321                            options, run_metadata)
   1322     else:
   1323       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1338         except KeyError:
   1339           pass
-> 1340       raise type(e)(node_def, op, message)
   1341
   1342   def _extend_graph(self):

PermissionDeniedError: /home/lemn/exp_data/lida/fast-style-transfer-master/save/111/111.ckpt.data-00000-of-00001.tempstate10799893154637130586
         [[Node: save/SaveV2 = SaveV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/SaveV2/tensor_names, save/SaveV2/shape_and_slices, Variable/_335, Variable/Adam/_337, Variable/Adam_1/_339, Variable_1/_341, Variable_1/Adam/_343, Variable_1/Adam_1/_345, Variable_10/_347, Variable_10/Adam/_349, Variable_10/Adam_1/_351, Variable_11/_353, Variable_11/Adam/_355, Variable_11/Adam_1/_357, Variable_12/_359, Variable_12/Adam/_361, Variable_12/Adam_1/_363, Variable_13/_365, Variable_13/Adam/_367, Variable_13/Adam_1/_369, Variable_14/_371, Variable_14/Adam/_373, Variable_14/Adam_1/_375, Variable_15/_377, Variable_15/Adam/_379, Variable_15/Adam_1/_381, Variable_16/_383, Variable_16/Adam/_385, Variable_16/Adam_1/_387, Variable_17/_389, Variable_17/Adam/_391, Variable_17/Adam_1/_393, Variable_18/_395, Variable_18/Adam/_397, Variable_18/Adam_1/_399, Variable_19/_401, Variable_19/Adam/_403, Variable_19/Adam_1/_405, Variable_2/_407, Variable_2/Adam/_409, Variable_2/Adam_1/_411, Variable_20/_413, Variable_20/Adam/_415, Variable_20/Adam_1/_417, Variable_21/_419, Variable_21/Adam/_421, Variable_21/Adam_1/_423, Variable_22/_425, Variable_22/Adam/_427, Variable_22/Adam_1/_429, Variable_23/_431, Variable_23/Adam/_433, Variable_23/Adam_1/_435, Variable_24/_437, Variable_24/Adam/_439, Variable_24/Adam_1/_441, Variable_25/_443, Variable_25/Adam/_445, Variable_25/Adam_1/_447, Variable_26/_449, Variable_26/Adam/_451, Variable_26/Adam_1/_453, Variable_27/_455, Variable_27/Adam/_457, Variable_27/Adam_1/_459, Variable_28/_461, Variable_28/Adam/_463, Variable_28/Adam_1/_465, Variable_29/_467, Variable_29/Adam/_469, Variable_29/Adam_1/_471, Variable_3/_473, Variable_3/Adam/_475, Variable_3/Adam_1/_477, Variable_30/_479, Variable_30/Adam/_481, Variable_30/Adam_1/_483, Variable_31/_485, Variable_31/Adam/_487, Variable_31/Adam_1/_489, Variable_32/_491, Variable_32/Adam/_493, Variable_32/Adam_1/_495, Variable_33/_497, Variable_33/Adam/_499, Variable_33/Adam_1/_501, Variable_34/_503, Variable_34/Adam/_505, Variable_34/Adam_1/_507, Variable_35/_509, Variable_35/Adam/_511, Variable_35/Adam_1/_513, Variable_36/_515, Variable_36/Adam/_517, Variable_36/Adam_1/_519, Variable_37/_521, Variable_37/Adam/_523, Variable_37/Adam_1/_525, Variable_38/_527, Variable_38/Adam/_529, Variable_38/Adam_1/_531, Variable_39/_533, Variable_39/Adam/_535, Variable_39/Adam_1/_537, Variable_4/_539, Variable_4/Adam/_541, Variable_4/Adam_1/_543, Variable_40/_545, Variable_40/Adam/_547, Variable_40/Adam_1/_549, Variable_41/_551, Variable_41/Adam/_553, Variable_41/Adam_1/_555, Variable_42/_557, Variable_42/Adam/_559, Variable_42/Adam_1/_561, Variable_43/_563, Variable_43/Adam/_565, Variable_43/Adam_1/_567, Variable_44/_569, Variable_44/Adam/_571, Variable_44/Adam_1/_573, Variable_45/_575, Variable_45/Adam/_577, Variable_45/Adam_1/_579, Variable_46/_581, Variable_46/Adam/_583, Variable_46/Adam_1/_585, Variable_47/_587, Variable_47/Adam/_589, Variable_47/Adam_1/_591, Variable_5/_593, Variable_5/Adam/_595, Variable_5/Adam_1/_597, Variable_6/_599, Variable_6/Adam/_601, Variable_6/Adam_1/_603, Variable_7/_605, Variable_7/Adam/_607, Variable_7/Adam_1/_609, Variable_8/_611, Variable_8/Adam/_613, Variable_8/Adam_1/_615, Variable_9/_617, Variable_9/Adam/_619, Variable_9/Adam_1/_621, beta1_power/_623, beta2_power/_625)]]

Caused by op 'save/SaveV2', defined at:
  File "/home/lemn/anaconda3/bin/ipython", line 6, in <module>
    sys.exit(IPython.start_ipython())
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/IPython/__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-109>", line 2, in initialize
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/IPython/terminal/ipapp.py", line 315, in initialize
    self.init_code()
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/IPython/core/shellapp.py", line 273, in init_code
    self._run_cmd_line_code()
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/IPython/core/shellapp.py", line 394, in _run_cmd_line_code
    self._exec_file(fname, shell_futures=True)
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/IPython/core/shellapp.py", line 328, in _exec_file
    raise_exceptions=True)
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2481, in safe_execfile
    self.compile if kw['shell_futures'] else None)
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/IPython/utils/py3compat.py", line 186, in execfile
    exec(compiler(f.read(), fname, 'exec'), glob, loc)
  File "/home/lemn/exp_data/lida/fast-style-transfer-master/style2.py", line 173, in <module>
    main()
  File "/home/lemn/exp_data/lida/fast-style-transfer-master/style2.py", line 153, in main
    for preds, losses, i, epoch in optimize(*args, **kwargs):
  File "src/optimize.py", line 136, in optimize
    saver = tf.train.Saver()
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1140, in __init__
    self.build()
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1172, in build
    filename=self._filename)
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 686, in build
    save_tensor = self._AddSaveOps(filename_tensor, saveables)
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 276, in _AddSaveOps
    save = self.save_op(filename_tensor, saveables)
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 219, in save_op
    tensors)
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 768, in save_v2
    tensors=tensors, name=name)
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/lemn/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

I'll be appreciated if you could help me.Thanks a lot!

**Comment by lengstrom** [comment]
you have file system permissions problems
