### ISSUE TITLE
Feature: Allow style transfer to images of different dimensions

### ISSUE THREAD

**Issue by cbonitz** [lengstrom/fast-style-transfer#12]
The current implementation creates one TF session with fixed input shape, and thus requires the input folder to only contain images of the same input size.

It would be useful to batch-process a folder with different input dimensions, using the minimum amount of TF sessions.

**Comment by lengstrom** [comment]
This is great, I'll review the code soon!

**Comment by lengstrom** [comment]
Thanks @cbonitz !
