### ISSUE TITLE
Train from checkpoint

### ISSUE THREAD

**Issue by Yagun** [lengstrom/fast-style-transfer#120]
Hi,

I like your project. 

I decided to train a new style, but then realized that it is going to take 16 hours on my GPU. I stopped the training in the middle of the process. There was stored checkpoint data. Later I started it again and expected that it will resume from the point it stopped. But it started training from scratch.

Please explain how to resume training from where it was stopped.

Thanks.

**Comment by lengstrom** [comment]
feature is not supported
