### ISSUE TITLE
Batch size and training quality

### ISSUE THREAD

**Issue by Yagun** [lengstrom/fast-style-transfer#121]
I tried to train with batchsize=20, but it failed. The I tried batchsize=2 and it works. Is there any formula to calculate the batch size? Some estimation related to GPU RAM?

Another question is: Does the training quality depend on batch size? In other words, is it better to train with larger batch to get better result?

Thanks.

**Comment by lengstrom** [comment]
Empirically, I haven't seen that training quality depends too much on batch size. As for max batch size, just see whatever works.

**Comment by spot92** [comment]
> I tried to train with batchsize=20, but it failed. The I tried batchsize=2 and it works. Is there any formula to calculate the batch size? Some estimation related to GPU RAM?
> 
> Another question is: Does the training quality depend on batch size? In other words, is it better to train with larger batch to get better result?
> 
> Thanks.

Did you ever find a max batch size for you? If yes, what is your GPU memory?
