### ISSUE TITLE
Content-weight used to train the styles

### ISSUE THREAD

**Issue by Yagun** [lengstrom/fast-style-transfer#122]
Default value of --content-weight is 7.5e0. In the example (how to run style.py) you use --content-weight 1.5e1. What value did you use to train those 6 styles: 7.5 or 15?

Thanks

**Comment by lengstrom** [comment]
I used a grid to train these styles.

**Comment by marcsyp** [comment]
How did you "use a grid"?  Sorry, n00b here.  :)

**Comment by wangshuai66666** [comment]
> I used a grid, not a single value.

How did you do it？"use a grid"？ @lengstrom

**Comment by fehmi** [comment]
The grid is a mystery for me too

**Comment by simonbuehler** [comment]
@lengstrom could you give a hint here?
