### ISSUE TITLE
Slow download of COCO dataset

### ISSUE THREAD

**Issue by ZachisGit** [lengstrom/fast-style-transfer#133]
Hi, I tried to download the mscoco dataset via the link provided in the setup.py
```
http://msvocds.blob.core.windows.net/coco2014/train2014.zip
```
and I got less then 1 MB/sec (I am in germany, so that might influence it).
I found an alternative link:
```
http://images.cocodataset.org/zips/train2014.zip
```
with this one I have over 7 MB/sec. But I am not sure if these are identical, could anybody verify that or provide an alternative to the first link? 

If anyone doesn't think this belongs in the Issues, feel free to remove it, just thought it might help some of you safe a couple of hours in download time :)

**Comment by wesleyw72** [comment]
You are right, that is much quicker. I verified they are exactly the same and have put in a pull request to change it in the repository.
[Pull request](https://github.com/lengstrom/fast-style-transfer/pull/134)
