### ISSUE TITLE
abnormal color block

### ISSUE THREAD

**Issue by suke27** [lengstrom/fast-style-transfer#149]
I found sometimes there are abnormal color block existed in transfer image

anybody how to remove this block?
![99_500](https://user-images.githubusercontent.com/30656046/39794825-d8c9963a-533b-11e8-8ec2-ca422121ffdd.png)

**Comment by lengstrom** [comment]
https://www.adobe.com/products/photoshop.html

**Comment by suke27** [comment]
are you kidding? haha

**Comment by lengstrom** [comment]
I'm sorry, here's a serious answer: This is an artifact of training and I don't know why it occurs sometimes. When this occurred for me I just trained longer and the inference artifacts generally disappear.

**Comment by Wojak27** [comment]
Has anyone solved this issue? On some of the models I still get it even after 10 epochs on 80k dataset
