### ISSUE TITLE
Lets share calculated Evaluation Models here?

### ISSUE THREAD

**Issue by DenisSergeevitch** [lengstrom/fast-style-transfer#15]
Please share links to your *.ckpt files here and please add sources from what image it were calculated

**Comment by lengstrom** [comment]
Hi Denis, `README.md` contains all this information.

**Comment by pidupuis** [comment]
The [`README`](https://github.com/lengstrom/fast-style-transfer/blob/master/README.md#evaluating-style-transfer-networks) refers to this [link](https://drive.google.com/drive/folders/0B9jhaT37ydSyRk9UX0wwX3BpMzQ).

**Comment by beraybentesen** [comment]
How do you create ckpt files ? Will it be created automatically after running style script ?
