### ISSUE TITLE
Memory management/slicing

### ISSUE THREAD

**Issue by techninja** [lengstrom/fast-style-transfer#16]
I have a budget GTX 950 with ~750 CUDA cores, it's pretty snappy and has enough CUDA support for **_some_** tensorflow experiments, but it only has 2GB of memory stock, and only about 1.7 free. This is gone pretty much instantly with any image over a certain size.

I do have 8 cores I can max with 16GB of system ram, and this has worked wonders using [neural-style-af](https://github.com/cysmith/neural-style-tf) for anything that needs more ram, though it does take ~12 hours to generate a 1024px wide image. What I want to do is create an image high enough resolution to actually be printed (175-300 DPI, > 5in), but unless the problem can actually split up into enough pieces, this is going to take impossibly long, or impossibly too many resources. 

Can we get a command line switch to use all available CPU cores instead of CUDA if I know I don't have enough memory? Or what would be amazing is some kind of solution to the memory problem, but my guess is that if you were do split an image into small slices each iteration would fail to match on the edges as the slices are non-continuous. I'd love any input on this :)

This is a good example image that fails with `ResourceExhaustedError`, it's about 8" @ 300DPI
![taj_mahal](https://cloud.githubusercontent.com/assets/320747/19951392/fab4ca5a-a11a-11e6-8901-305059ddcc24.jpg)

**Comment by lengstrom** [comment]
In `evaluate.py` the device used for computation is controlled by the `--device` flag. If you pass `/cpu:0` you should use every available CPU for evaluation (or at least that's what happens on my machine). As for slicing, that would have to be a TensorFlow related feature, unfortunately I don't have much control there. I think that TensorFlow will just give you an OOM exception if TensorFlow can't fit all the tensors in memory. You could look up documentation for splitting up calculations though, and submit a pull request if you find anything (`ffwd` is the method that you should look at in `evaluate.py` if you want to try to solve this)
