### ISSUE TITLE
Input image preprocessing

### ISSUE THREAD

**Issue by agrimgupta92** [lengstrom/fast-style-transfer#18]
In optimize.py the input content image is divided by 255 before passing it though the transform net. We don't do something similar in evaluate.py. Also, we never do unprocess the output images. Is this by design? Or the scaling and shifting after tanh takes care of these two things.

**Comment by lengstrom** [comment]
We learn the style transfer function directly so unprocessing is unnecessary in evaluation. Empirically, preprocessing for the transformation network doesn't matter so much, the scaling is mainly meant for better backpropagation.

**Comment by agrimgupta92** [comment]
Thanks for the clarification!
