### ISSUE TITLE
how i can run this software at AWS

### ISSUE THREAD

**Issue by saydulk** [lengstrom/fast-style-transfer#184]
Hello, i have setup all dependency and run setup.sh file and it successfully compile into Ubuntu 16.04

Now how i can brows the software from IP Address. i am using AWS Ubuntu 16.04 LTS Linux

**Comment by JEF1056** [comment]
`git clone https://github.com/lengstrom/fast-style-transfer.git`
then CD into the directory, and run training using the code provided on the front page:
```
python style.py --style path/to/style/img.jpg \
  --checkpoint-dir checkpoint/path \
  --test path/to/test/img.jpg \
  --test-dir path/to/test/dir \
  --content-weight 1.5e1 \
  --checkpoint-iterations 1000 \
  --batch-size 20```

**Comment by saydulk** [comment]
Thanks @JEF1056

**Comment by JEF1056** [comment]
Np!
