### ISSUE TITLE
can we port this into mobile?

### ISSUE THREAD

**Issue by markz-nyc** [lengstrom/fast-style-transfer#19]
After finishing training model, can we run this transfer on iOS app?

**Comment by lengstrom** [comment]
sure, it would take 30 sec to a few minutes to run for your average iPhone photo though!

**Comment by markz-nyc** [comment]
Thanks for the reply, can I use Ulyanov's model here? Or I need to train model again?

**Comment by markz-nyc** [comment]
Also how hard to wrap it up into a mobile environment like iOS? I mean iOS doesn't have good loadcaffe framework, not sure it tensor flow works...

**Comment by lengstrom** [comment]
> Thanks for the reply, can I use Ulyanov's model here? Or I need to train model again? 
No idea, I don't know what his model is

> Also how hard to wrap it up into a mobile environment like iOS? I mean iOS doesn't have good loadcaffe framework, not sure it tensor flow works...
I've never done this before

**Comment by mdramos** [comment]
i've done this, takes a few seconds with the current model:

https://medium.com/@rambossa/diy-prisma-fast-style-transfer-app-with-coreml-and-tensorflow-817c3b90dacd

https://github.com/mdramos/fast-style-transfer-coreml
