### ISSUE TITLE
Wrong flags name in docs

### ISSUE THREAD

**Issue by Neutrino3316** [lengstrom/fast-style-transfer#206]
In <https://github.com/lengstrom/fast-style-transfer/blob/master/docs.md#stylepy>

> - `--batch_size`: Batch size for training. Default: `4`.

The spelling is not correct. It should be linked by hyphen rather than a underline. Here it what it should be:

> - `--batch-size`: Batch size for training. Default: `4`.

**Comment by lengstrom** [comment]
pull request welcome!

**Comment by Neutrino3316** [comment]
> pull request welcome!

**Comment by Neutrino3316** [comment]
> pull request welcome!

I pulled a request, you may check and merge it. Thank you.

**Comment by lengstrom** [comment]
fixed! thanks!
