### ISSUE TITLE
What are the good choices for those parameters in the style.py?

### ISSUE THREAD

**Issue by michaelhuang74** [lengstrom/fast-style-transfer#21]
Because the training process by running style.py may take 4-6 hours on even a decent GPU, say Tesla K40, I want to get some ideas regarding the good choices for those parameters in the style.py.

1. lengstrom defines the default values of the parameters in style.py. Are the default values are generally good for general cases? In other words, if using the default values, will the generated model file be good enough to stylize images using the evaluate.py?

I also have a couple additional questions regarding some specific parameters.

2.  What is the good choice of the "checkpoint-iterations" parameter? The default value is 2000. In the example given by lengstrom in the README.md, it is 1000. Are 1000 iterations good enough to generate a good model file, or the training step has to go through 2000 iterations to generate a good model file?

3. The "batch-size" parameter. The default value is 20. The value used in the example in the README.md is 4. For the 12 GB memory available on K40, what is a good value for batch-size?

4. The "content-weight" parameter. Similarly, the default value (7.5e0) is different from the value (1.5e1) in the example in the README.md. Which value is better? 

Thanks in advance for any help!

**Comment by lengstrom** [comment]
1. The hyperparameters take some tuning to get good results
2. The checkpoint-iterations parameter only controls how often checkpoints are taken, it has nothing to do with the model files you generate
3. As high a batch size you can fit in your GPU as possible, although I'm not sure as to what program you're talking about
4. See 1
