### ISSUE TITLE
TensorFlow 2.0 Implementation

### ISSUE THREAD

**Issue by justinrmiller** [lengstrom/fast-style-transfer#225]
Greetings,

I have an implementation of evaluate.py and associated libraries that I've converted to TensorFlow 2.0. Would you be interested in potentially merging this in or would you prefer I create a separate project for that?

Thanks,
Justin

**Comment by lengstrom** [comment]
That would be awesome! I am happy to help as well.

**Comment by Akirakato1** [comment]
Do  you happened to have changed style.py for tf 2.0 too?

**Comment by justinrmiller** [comment]
I will try to get that going as well and also test the evaluate file with video files.

**Comment by naveen-annam** [comment]
> I will try to get that going as well and also test the evaluate file with video files.

@justinrmiller  hey justin. Any update on this?. Didn't have much luck converting it to use 2.0. Would be really help if you update this somewhere with 2.0.

**Comment by justinrmiller** [comment]
Sorry things have been a bit busy lately. I will try to get a PR together this weekend. I have not tested video or model training but will try to do that soon.

**Comment by naveen-annam** [comment]
@justinrmiller Updated with 2.0 code. https://github.com/lengstrom/fast-style-transfer/pull/239. Got it to work with @divisiondeariza scipy fix and using the utility.

**Comment by justinrmiller** [comment]
Yeah it looks like you went with a strategy similar to mine and applied the TF2 upgrade tool. The only other change I had to make it make it work was around “.value” which it looks like you’ve taken care of as well. Good work!

**Comment by rmasiso** [comment]
How did you use the TF2 upgrade tool?

**Comment by justinrmiller** [comment]
@naveen-annam Looks like your PR got merged down, going to close this one down. Thanks!
