### ISSUE TITLE
Generate grey output after training the style image with epochs=1

### ISSUE THREAD

**Issue by michaelhuang74** [lengstrom/fast-style-transfer#24]
I trained the following style image using the below command on Nvidia Tesla K40.
python style.py --style examples/style/the_scream.jpg --epochs 1  --checkpoint-dir checkpoint/  --batch-size 20

![image](https://cloud.githubusercontent.com/assets/23154573/20445575/3c92eb64-ad9b-11e6-86e2-a659b04e0655.png)

Then I used the generated model file to stylize the image of Chicago landscape. The output is grey image as follows.

![image](https://cloud.githubusercontent.com/assets/23154573/20445719/dedfd03a-ad9b-11e6-8ba4-3655d622e3ec.png)

When training the style image with epochs=1, is the output image always grey? Do we have to train the style image for epochs=2?

**Comment by lengstrom** [comment]
That doesn't look right, unsure why you're getting that output. # epochs
should not matter in terms of greyscale vs color.

**Comment by michaelhuang74** [comment]
@lengstrom Do you think that greyscale output might be due to different versions of scipy?

I am using python 2.7. The version of scipy installed with python 2.7 is 0.13.3. 
When I downloaded your code, there were errors for executing the following scipy api:
scipy.misc.imread(src, mode='RGB')

I changed it to scipy.misc.imread(src,'RGB') without upgrading scipy and the error was gone.

Which version of scipy do you use for training style images?

P.S.: It seems that even with python 2.7 with scipy 0.13.3, the evaluate.py is able to generate color output by using the model files downloaded from the google drive.

**Comment by lengstrom** [comment]
I don't think its your scipy, I'm not sure why you're having this issue. Try putting a debugger in the `imsave` part of the code.

**Comment by michaelhuang74** [comment]
After upgrading scipy to 0.18.1, the generated model file is able to produce color output.

The prototype of scipy.misc.imread in 0.13.3 is scipy.misc.imread(name, flatten=0).
In 0.18.1, it is changed to scipy.misc.imread(name, flatten=False, mode=None).

Under scipy 0.13.3, executing scipy.misc.imread(src, mode='RGB') will encounter an error. Changing it to scipy.misc.imread(src,'RGB'), the error is gone. But 'RGB' is treated as the second argument (i.e., flatten=1). Then the color layers are flattened into a single gray-scale layer. This will result in a model file that produces gray-scale output.
