### ISSUE TITLE
Are there ways to speedup the training process?

### ISSUE THREAD

**Issue by michaelhuang74** [lengstrom/fast-style-transfer#26]
It seems that the models that are generated using "epochs=2" can produce very good output images. I tried to train the models using "epochs=1" and found the quality of the output images (produced by evaluate.py) is not as good as with the models using "epochs=2".

With "epochs=2", Titan-X (Maxwell) can finish the training process in about 5 hours. Tesla K40/K80 will need almost 2 times the period, i.e., 10 hours. This is due to two reasons. (1) Only single-precision floating point operations are used in the training process. The good double-precision floating point performance on K40/K80 does not help. (2) The clock frequency of GPU cores on K40/K80 is only half of the clock frequency of GPU cores on the Maxwell architecture. 

5 hours on Titan X (or 10 hours on K40/K80) are very long periods.  Are there ways to optimize the algorithm so that good model files can be generated in short periods?

**Comment by lengstrom** [comment]
I haven't really thought about optimizing the training process too much. One thing you could try is only loading the vgg network into the GPU once rather than twice as is done now. If you do find anything it would be great if you could feed your changes back into the codebase!

**Comment by michaelhuang74** [comment]
@lengstrom Thanks for the reply. Could you be more specific on (1) where in optimize.py the vgg network is loaded twice (e.g., lines 47 and 59?), (2) how it can be loaded only once?
