### ISSUE TITLE
Does the training run on multiple GPUs in the same computer system?

### ISSUE THREAD

**Issue by michaelhuang74** [lengstrom/fast-style-transfer#27]
The style.py does not provide the argument "--device" to specify on which device the training will run. 

If there are multiple GPUs in the same computer system,
(1) Will a single training task run on multiple GPUs distributively?
(2) If a single training task runs on a single GPU and I run multiple training tasks in parallel, are they all going to run on the same GPU device?

**Comment by lengstrom** [comment]
I think TF will expand to fill every GPU but I don't know, you'll just have
to figure it out by trial/error and looking at the code.
