### ISSUE TITLE
Program gets killed. 

### ISSUE THREAD

**Issue by jadonalam** [lengstrom/fast-style-transfer#274]
Hi. After a few hours after I run this: 

`python style.py --style /Users/owner/Documents/2_fast-style-transfer-master/la_muse.jpg --checkpoint-dir /Users/owner/Documents/2_fast-style-transfer-master --test /Users/owner/Documents/2_fast-style-transfer-master/mars.jpg --test-dir /Users/owner/Documents/2_fast-style-transfer-master --content-weight 7.5e0 --checkpoint-iterations 6000 --epochs 2 --batch-size 1 --train-path /Users/owner/Documents/2_fast-style-transfer-master/train2014 --vgg-path /Users/owner/Documents/2_fast-style-transfer-master/imagenet-vgg-verydeep-19.mat`

my program gets killed. 

Does anyone have any ideas as to why this happens? 

Thanks in advance.

**Comment by impactcolor** [comment]
Usually when it gets killed it's related to memory.
