### ISSUE TITLE
Can i know what is the function (transform.net(image) (./src/transform.py line5) doing?

### ISSUE THREAD

**Issue by EternalNation** [lengstrom/fast-style-transfer#28]
Can i know what is the function (transform.net(image) (./src/transform.py line5)) doing?
Its network structure looks not same as VGG network.
It seems training with VGG network and feed-forwarding (stylizing phase) to other(transform.net) network.
And i can't understand how it works.
Thank you.

**Comment by lengstrom** [comment]
You should read the code in the `net` function in`transform.py`.
