### ISSUE TITLE
Green and red dot pattern are appearing

### ISSUE THREAD

**Issue by JLoRenderer** [lengstrom/fast-style-transfer#281]
![green-red2](https://user-images.githubusercontent.com/36763834/159997177-cc814a18-9f9a-4dc9-bb57-faecfd33ca90.jpg)

These green an red dot pattern appear in some parts of the image generated by my trained model.

Could somebody give me a hint on how to fix this?

**Comment by lengstrom** [comment]
You also might be able to filter images ahead of time (maybe a high pass filter?).

**Comment by Wojak27** [comment]
Did this solve the issue?
