### ISSUE TITLE
ERROR 409: Public access is not permitted on this storage account..

### ISSUE THREAD

**Issue by danuonuo** [lengstrom/fast-style-transfer#289]
Hi, when I'm running the setup.sh, I faced this error:

`--2023-07-15 14:07:01--  http://msvocds.blob.core.windows.net/coco2014/train2014.zip
Resolving msvocds.blob.core.windows.net (msvocds.blob.core.windows.net)... 20.60.195.163
Connecting to msvocds.blob.core.windows.net (msvocds.blob.core.windows.net)|20.60.195.163|:80... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.
2023-07-15 14:07:01 ERROR 409: Public access is not permitted on this storage account..`

How should I fix this?
Thanks.

**Comment by paradiseforgithub** [comment]
已收到您的邮件,如有问题会尽快给您回复.

**Comment by paradiseforgithub** [comment]
已收到您的邮件,如有问题会尽快给您回复.
