### ISSUE TITLE
Alternative Hosting for Evaluation Models

### ISSUE THREAD

**Issue by minimaxir** [lengstrom/fast-style-transfer#3]
Dropbox Public Sharing has a [bandwidth limit](https://www.dropbox.com/help/4204) of 20GB or 200GB bandwidth per day; with the six 20MB models [included with the repo](https://www.dropbox.com/sh/exlysa7n1j397fp/AACl7lXX4mkTBZP14uX709Npa?dl=0), that limit will be hit very quickly if the repo gains traction (which I think it will).

I believe Google Drive has generous bandwidth limits.

**Comment by lengstrom** [comment]
Fixed in https://github.com/lengstrom/fast-style-transfer/commit/651a01696bccd84cb66780fcf104b874ff267b1e, thanks!
