### ISSUE TITLE
Running on iOS

### ISSUE THREAD

**Issue by MrZoidberg** [lengstrom/fast-style-transfer#32]
Since TensorFlow [works on iOS,](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile) is it possible to run your fast-style on iOS?

Thanks!

**Comment by MrZoidberg** [comment]
Figured out that it's impossible without a complete rewrite

**Comment by mike1808** [comment]
@MrZoidberg can you tell why do you need complete rewrite?

**Comment by MrZoidberg** [comment]
@mike1808, there is no good Python implementation for iOS, so I'll need to rewrite fast-style-transfer to Objective-C or Swift to be able to run fast-style algorithms on iOS.

**Comment by ShushanArakelyan** [comment]
I'm not sure, what you mean, but I assume, you're looking for a way to run the feed-forward part on mobile. For that you actually can save the trained model using Tensorflow graph load/write interface, freeze it, then load and run it in your Objective-C application. Tensorflow mobile examples do that for a pretrained ImageNet, you can check those for more details on how that should be done. 
I'm sorry, if my initial assumption was wrong and you were looking for something different, then my answer is inappropriate.

**Comment by dovanchan** [comment]
@MrZoidberg  I think if you try to run fast-neural-style in iphone,It will be spent so much time in every eval.py ;So I suggest you should buy a GPU instance for the user experience；how do you think ?
