### ISSUE TITLE
Ran out of memory trying to allocate 3.27GiB.

### ISSUE THREAD

**Issue by MrZoidberg** [lengstrom/fast-style-transfer#33]
I'm trying to run a sample styling and have a problem when running on GPU. I have GTX 760 with 2 GB RAM. Here are my logs:

`python evaluate.py --checkpoint data/models/udnie.ckpt --in-path examples/content/ --out-path examples/ --allow-different-dimensions --device /gpu:0 --batch-size 1
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cublas64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cudnn64_5.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library cufft64_80.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library nvcuda.dll locally
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\dso_loader.cc:128] successfully opened CUDA library curand64_80.dll locally
in
['examples/content/chicago.jpg']
out
['examples/chicago.jpg']
Processing images of shape 474x712x3
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:885] Found device 0 with properties:
name: GeForce GTX 760
major: 3 minor: 0 memoryClockRate (GHz) 1.15
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.65GiB
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:906] DMA: 0
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:916] 0:   Y
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 760, pci bus id: 0000:01:00.0)
E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:586] Could not identify NUMA node of /job:localhost/replica:0/task:0/gpu:0, defaulting to 0.  Your kernel may not have been built with NUMA support.
W c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\bfc_allocator.cc:217] Ran out of memory trying to allocate 3.27GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.`

Is there anything I can do except buying a new graphics card?

**Comment by storkme** [comment]
please see #10

**Comment by MrZoidberg** [comment]
@storkme so some of the sample models need 12GB GPU to work?

**Comment by armoreal** [comment]
Try to use smaller content image (like 200x200px  )
I have 8GB GPU but got the same errors when tried to use images bigger than 2500x1700px.

**Comment by lengstrom** [comment]
You should probably buy a better graphics card.

**Comment by theqihao** [comment]
I have the same issues, I want to know what that mean?,why it still can run with the warning of run out of memory? @MrZoidberg @lengstrom @armoreal @tibbon
