### ISSUE TITLE
debugging loss function error

### ISSUE THREAD

**Issue by armoreal** [lengstrom/fast-style-transfer#38]
Seems there's some code missed in "style.py".
When tried to run it with "--slow" flag got this error:
`Traceback (most recent call last):
  File "style.py", line 170, in <module>
    main()
  File "style.py", line 164, in main
    save_img(preds_path, img)
NameError: global name 'img' is not defined`

**Comment by lengstrom** [comment]
Thanks for heads up, this is a real issue, I'll get around to fixing this later.

**Comment by nwvaras** [comment]
I think this is still a bug?

**Comment by RobertGoacher** [comment]
Can confirm; this is still not working. @lengstrom could you change the status of this issue to open please?
