### ISSUE TITLE
No checkpoint model

### ISSUE THREAD

**Issue by harry0731** [lengstrom/fast-style-transfer#39]
Hello, thank you for your amazing work.
After I run the style.py.
It shows Training complete. 
But I can't find the .ckpt file at the directory.

Any suggestions ?
Thank you.

**Comment by lengstrom** [comment]
Can you please be more specific?

**Comment by harry0731** [comment]
I put the checkpoint directory here.
--checkpoint-dir ~/Desktop/fast-style-transfer-master/
But after training there isn't any model files.
So I can't evaluate images.

**Comment by jbgrant01** [comment]
When I completed a training cycle (4 days) in my Ckpt directory there were four files: checkpoint, fns.ckpt-00000-00001 (or something similar). fns.ckpt.index, and fns.ckpt.metadata. Seems like it should have a simple fns.ckpt, similar to the included models like la_muse.ckpt.

How do I build a fns.ckpt file to use with evaluate?

**Comment by lengstrom** [comment]
@harry0731 It works for me, I don't know what you're doing wrong. 

@jbgrant01 You can just pass the directory into the evaluation script.

**Comment by haikuoyao** [comment]
I have the same question with @jbgrant01 
How did you create just one single tensorflow model file?
Thanks.

**Comment by lewisdonovan** [comment]
I'm stuck on this too. I've got the same set of files that @jbgrant01 described. I passed the checkpoint directory into the evaluation script and it output the stylised images, but I still have no '.ckpt' file. I've tried `sudo ls` in the checkpoint directory but still see the same file list.

Here's the command I used to evaluate the checkpoint:
```
sudo python evaluate.py --checkpoint path/to/checkpoints --in-path path/to/images --out-path path/to/output --allow-different-dimensions
```

My `checkpoint` file (no file extension) has the following inside:
```
model_checkpoint_path: "fns.ckpt"
all_model_checkpoint_paths: "fns.ckpt"
```

But `fns.ckpt` does not exist in this folder.

**Comment by liaquat85** [comment]
can you just upload the checkpoints files like I have the file as rain-princess.cpkt

**Comment by larrybrit** [comment]
This fixed the problem for me.
https://github.com/lengstrom/fast-style-transfer/issues/78#issuecomment-302307215

**Comment by spot92** [comment]
> When I completed a training cycle (4 days) in my Ckpt directory there were four files: checkpoint, fns.ckpt-00000-00001 (or something similar). fns.ckpt.index, and fns.ckpt.metadata. Seems like it should have a simple fns.ckpt, similar to the included models like la_muse.ckpt.
> 
> How do I build a fns.ckpt file to use with evaluate?

Did you solve this? I am looking to not retrain with the code referenced by larrybrit, but use the files I already have some how

**Comment by spot92** [comment]
> @jbgrant01 You can just pass the directory into the evaluation script.

I tried this and got nowhere.
