### ISSUE TITLE
Not an issue - Typo in docs.md

### ISSUE THREAD

**Issue by jbgrant01** [lengstrom/fast-style-transfer#41]
In docs.md the first flag for style.py should be '--checkpoint-dir', not '--checkpoint'. Also getting a whine for line 91 of src/optimize.py that initialize.all.variables needs to be updated to tf.global.variables.initializer. Haven't tried it myself. My slow system is working on stylizing a Van Gogh painting. About 18 hours into it on epoch 0, 10000 iterations. Not much stylizing on the test image as yet. I am using the defaults in style.py.

**Comment by lengstrom** [comment]
Fixed.
