### ISSUE TITLE
error on training images

### ISSUE THREAD

**Issue by mike-pastore** [lengstrom/fast-style-transfer#46]
The `setup.sh` script did not work so I manually created the directories and downloaded the VGG network and training images into the default file paths. However when I run `style.py` I get this error:

```
Traceback (most recent call last):
  File "style.py", line 166, in <module>
    main()
  File "style.py", line 146, in main
    for preds, losses, i, epoch in optimize(*args, **kwargs):
  File "src\optimize.py", line 18, in optimize
    mod = len(content_targets) % batch_size
TypeError: object of type 'map' has no len()
```

I believe `content_targets` is supposed to take the individual images into an `xrange`, but it is not happening. Do you know why it's becoming a 'map' object type instead?

**Comment by nvki** [comment]
I'm assuming you are using python 3.5 - the supplied code is for 2.7.9. Amongst many other things the map() function in 3.5 is a generator object and does not return a list anymore. For more information read [this](http://stackoverflow.com/questions/13638898/how-to-use-filter-map-and-reduce-in-python-3).
I (crudely) adapted the style, evaluate and optimize scripts to run with Python 3.5 and could send them to you

**Comment by mike-pastore** [comment]
nvki you're right, I'm using 3.5--i started appling len() to the map()s and got some further progress, but still hitting a wall. 

I would very much appreciate your 3.5 adaptations of style, evaluate, and optimize.py!

**Comment by nvki** [comment]
there you go! 
I changed the path to the COCO dataset within style.py so you will have to adjust that. I only got to change the style and evaluate scripts but theres a pull request with a py35 version of transform_video by Schwusch
[fast-style-transfer_py35.zip](https://github.com/lengstrom/fast-style-transfer/files/742728/fast-style-transfer_py35.zip)

**Comment by mike-pastore** [comment]
thanks so much--this works flawlessly after i updated the path to the dataset!
