### ISSUE TITLE
Noise is generated in the picture.

### ISSUE THREAD

**Issue by leeys888** [lengstrom/fast-style-transfer#47]
I have been training and testing several style images.
However, noise is generated as shown below, where is the problem?
![image](https://cloud.githubusercontent.com/assets/7201624/22577855/d9588f28-ea07-11e6-8a18-e3417e03e613.png)
![image](https://cloud.githubusercontent.com/assets/7201624/22577901/fb94b53a-ea07-11e6-9b61-f81ae90692fe.png)

**Comment by lengstrom** [comment]
You should train more to get rid of those artifacts.

**Comment by leeys888** [comment]
There are a total of 80,000 learning images, so can we learn by increasing the number of epochs?

**Comment by lengstrom** [comment]
Yes, or by adding more images.

**Comment by SunAnLan** [comment]
Did you finally get rid of this? I got the same phenomen
