### ISSUE TITLE
KeyError: 'normalization'

### ISSUE THREAD

**Issue by beraybentesen** [lengstrom/fast-style-transfer#49]
Traceback (most recent call last):
  File "style.py", line 166, in <module>
    main()
  File "style.py", line 146, in main
    for preds, losses, i, epoch in optimize(*args, **kwargs):
  File "src/optimize.py", line 33, in optimize
    net = vgg.net(vgg_path, style_image_pre)
  File "src/vgg.py", line 27, in net
    mean = data['normalization'][0][0][0]
KeyError: 'normalization'

**Comment by futouyiba** [comment]
Hey @beraybentesen , could you tell how this was solved? Cuz I'm running into the same issue.

**Comment by beraybentesen** [comment]
@futouyiba I was using wrong VGG file. Re-downloaded and problem fixed.

**Comment by robotdude17** [comment]
I'm having the same issues, called it with the following args:

python style.py --style ./model/rd_01.jpg --checkpoint-dir ./model/ --test ./img_src/20161204_124022_1397.jpg --test-dir ./img_out/ --vgg-path /data/scripts/Udacity/Style-Transfer/fast-style-transfer-master/data/imagenet-vgg-verydeep-19.mat --content-weight 1.5e1 --checkpoint-iterations 1000 --batch-size 20

I also re-downloaded the VGG file from

http://www.vlfeat.org/matconvnet/pretrained/

and made sure they are there:

(style-transfer) ...@.../data/scripts/Udacity/Style-Transfer/fast-style-transfer-master$ ls dataimagenet-vgg-verydeep-16.mat  imagenet-vgg-verydeep-19.mat

Could you please help?

Thanks a lot!

**Comment by futouyiba** [comment]
Worked for me, also!

**Comment by alpeshvasani** [comment]
Can you provide like here for correct VGG file?
