### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by beraybentesen** [lengstrom/fast-style-transfer#50]
Can't we create own model file ? checkpoint folder is empty after running style script.

**Comment by lengstrom** [comment]
Yes, the checkpoint is saved in the checkpoint folder.

**Comment by beraybentesen** [comment]
@lengstrom After running following code, I think I should be getting model file inside van-gogh folder right ? 

sudo python style.py --checkpoint-dir ./checkpoint/van-gogh --style ./styles/van-gogh/style-starry-night.jpg  --content-weight 1.5e1 --checkpoint-iterations 1000 --batch-size 12 --vgg-path ./imagenet-vgg-verydeep-19.mat --epochs 2

But nothing happens after 2-3 hours training.
