### ISSUE TITLE
Can't run evaluate.py on gpu

### ISSUE THREAD

**Issue by Keloo** [lengstrom/fast-style-transfer#53]
I run: python evaluate.py --batch-size 1 --device /gpu:0 --checkpoint models/wave.ckpt --in-pat <img_path> --out-path <img_out_path>

It takes more than 3 seconds, I monitor the loading and only the processor is loaded.
It looks like it fallback to using the cpu.
I have an Intel i7 as cpu and gpu: Titan X

**Comment by lengstrom** [comment]
This works for me, there's probably some driver issue you have.
