### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'JpegImageFile' and 'JpegImageFile'

### ISSUE THREAD

**Issue by overboming** [lengstrom/fast-style-transfer#54]
I have been trying to train a new model using `python style.py --checkpoint-dir checkpoint --style examples/style/test.jpg --train-path train2014 --content-weight 1.5e1 --checkpoint-iterations 1000 --batch-size 15` and counted this issue, 

Latest version of tensorflow 1.0.0 
Python 2.7.12
Pillow 4.0.0

> Traceback` (most recent call last):
>   File "style.py", line 167, in <module>
>     main()
>   File "style.py", line 147, in main
>     for preds, losses, i, epoch in optimize(*args, **kwargs):
>   File "src/optimize.py", line 105, in optimize
>     X_batch[j] = get_img(img_p, (256,256,3)).astype(np.float32)
>   File "src/utils.py", line 20, in get_img
>     img = scipy.misc.imresize(img, img_size)
>   File "/home/malic/ml/local/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 478, in imresize
>     im = toimage(arr, mode=mode)
>   File "/home/malic/ml/local/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 341, in toimage
>     bytedata = bytescale(data, high=high, low=low, cmin=cmin, cmax=cmax)
>   File "/home/malic/ml/local/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 90, in bytescale
>     cscale = cmax - cmin
> TypeError: unsupported operand type(s) for -: 'JpegImageFile' and 'JpegImageFile'
> 

It seems like Pillow is not working correctly when doing `imresize`, which version should I be using or try to use the original version of PIL

**Comment by overboming** [comment]
It turns out the coco image set train2014.zip archive has a corrupted image that will cause this issue.

Image name was 000000167126.jpg, anyone met this issue just remove the image and it will run smoothly

**Comment by petteriTeikari** [comment]
I got the same error, and with the following `corruption hunting` call:

`find . -name \*.jpg -exec identify -verbose -regard-warnings {} >/dev/null "+"`

I also found the file `COCO_train2014_000000241622.jpg` from train2014 which was causing the problem

```bash
identify: Premature end of JPEG file `./COCO_train2014_000000241622.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
identify: Corrupt JPEG data: premature end of data segment `./COCO_train2014_000000241622.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
```

**Comment by AshlyAngel** [comment]
i didn't get a good model after training the stylized image /video is not good the style is not transferred why
