### ISSUE TITLE
Is it possible to use tensorflow serving to serve this model?

### ISSUE THREAD

**Issue by cheyang** [lengstrom/fast-style-transfer#55]
I'm wondering if it's possible to use serving to serve the model with [regression method](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/signature_constants.py#L64). Thanks. 

I mean that if we can export the model like [exporting mnist to TensorFlow serving](https://tensorflow.github.io/serving/serving_basic.html), and use GRPC server to serve it. Do you think if it's possible?

**Comment by lengstrom** [comment]
Please explain more, I don't know what you mean.

**Comment by cheyang** [comment]
any ideas？

**Comment by dogeunderground** [comment]
You might want to consider using the techniques described in [this paper](http://sigtbd.csail.mit.edu/pubs/2016/paper5.pdf).
