### ISSUE TITLE
preds = tf.nn.tanh(conv_t3) * 150 + 255./2

### ISSUE THREAD

**Issue by sguuaa** [lengstrom/fast-style-transfer#57]
preds = tf.nn.tanh(conv_t3) * 150 + 255./2
what does this mean?

**Comment by tonypeng** [comment]
some say it is a mystery best left to the gods

**Comment by kevfoley** [comment]
Its just an activation performed on the final layer. It introduces a non-linearity...

**Comment by sguuaa** [comment]
I think
preds = tf.nn.tanh(conv_t3) * 150 + 255./2
should be
preds = tf.nn.tanh(conv_t3) * 127.5 + 255./2
