### ISSUE TITLE
evaluate.py: "IOError: cannot identify image file '.DS_Store'"

### ISSUE THREAD

**Issue by minimaxir** [lengstrom/fast-style-transfer#6]
It may be worth it to add a file extension check to files loaded, if possible, from the `in-path` specified in `evaluate.py` to reduce problems in OSX. (in the meantime, `rm .DS_Store` in the Terminal fixes the issue)

**Comment by lengstrom** [comment]
I think people should be able to figure out that this is their problem, and fix it on their own. I don't want to make specifications too specific for what files should / shouldn't be processed, and I don't want to maintain a list of extensions to ignore, etc. Do you think this is reasonable?
