### ISSUE TITLE
Where the pretrained models trained with the default values of the script?

### ISSUE THREAD

**Issue by bryant1410** [lengstrom/fast-style-transfer#67]

**Comment by rishabhjain** [comment]
Some pretrained models [here](https://drive.google.com/drive/folders/0B9jhaT37ydSyRk9UX0wwX3BpMzQ?usp=sharing). Not sure if it uses default values of the script for training though.

**Comment by lengstrom** [comment]
The pretrained models were trained using a grid search over a small parameter space roughly centered around the default values (logarithmically).

**Comment by bryant1410** [comment]
Can you add that to the readme? And also the parameters space tried?

**Comment by ofirbb** [comment]
+1 on this, can you give the parameters of your grid search? It seems to me that between all the other parameters in pursuing good styles, these might be very useful.

**Comment by brannondorsey** [comment]
I would indeed like to know the values for the grid searches as well as the code implementation of such a search if they are available. This would indeed be very useful in my work.

**Comment by zougamohamed** [comment]
+1 on this
