### ISSUE TITLE
'module' object has no attribute 'stack' on latest TensorFlow

### ISSUE THREAD

**Issue by x8BitRain** [lengstrom/fast-style-transfer#68]
I followed the advice on this problem and updated my tensorflow to the one listed here: https://www.tensorflow.org/install/install_linux#the_url_of_the_tensorflow_python_package
with GPU support, If I install tensorflow via "pip install tensorflow/tensorflow-gpu it is unable to find the CUDA libs so installing the latest mentioned version via a wheel package finds the CUDA files properly but I still get the AttributeError: 'module' object has no attribute 'stack' error.

Yes, I've tried setting environment variables for CUDA to make Tensorflow detect it but it just does not work. Here's the log: https://pastebin.com/Pqca0QzM

Any ideas?

**Comment by xiayq1** [comment]
I meet this problem, too.

**Comment by patthai** [comment]
I have this problem as well :(

**Comment by patthai** [comment]
I have resolved the problem by updating Tensorflow to current version.

**Comment by vaibhavgeek** [comment]
Has anyone solved this particular issue?

**Comment by billautomata** [comment]
I hope this doesn't re-open the ticket but using the latest tensorflow fixed this for me, the docs in the readme say 0.11.0, but that's not what I'm using, I'm using 1.6
