### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by tibbon** [lengstrom/fast-style-transfer#7]
Currently installing this is a bear otherwise.

**Comment by lengstrom** [comment]
What aspects of installing the requirements to run this project are most difficult/opaque?

**Comment by tibbon** [comment]
Python isn't my native language, so figuring out the various required versions for each package, how to best install them, etc is relatively tricky. 

I guess I'm just used to `bundle install` in Ruby :)

**Comment by lengstrom** [comment]
You're welcome to make a community wiki page if you want! However I don't want to maintain how to install the dependencies in the repository.

**Comment by fenollp** [comment]
@lengstrom What is your rationale behind this stand?
No mention of the semver of a project's dependencies is eventually similar to not mentioning dependencies at all, I would say.
I would add that this dependencies information is exactly what you want to have in sync with your codebase.

**Comment by lengstrom** [comment]
I've added the versions of the libraries necessary that I use on my server in this commit: https://github.com/lengstrom/fast-style-transfer/commit/22acb38354715ef268c3583115bc3c4fe49426e8. Hope this helps!
