### ISSUE TITLE
Handle Transparency in evaluate.py

### ISSUE THREAD

**Issue by jonobr1** [lengstrom/fast-style-transfer#71]
I've got fast-style-transfer running and it's so awesome to see the results! I've made my own checkpoint and love tweaking the values. I was wondering, is there a way to handle transparent PNGs or GIFs so that when `alpha = 0` the style transfer isn't applied?

**Comment by jonobr1** [comment]
So I noticed that you can change the format handled for the incoming images here: https://github.com/lengstrom/fast-style-transfer/blob/master/src/utils.py#L16 which I changed from `RGB` to `RGBA` based on the SciPy documentation. I get a new error saying `Assign requires shapes of both tensors to match`. My hunch is that I need to generate a checkpoint that's also `RGBA` format. Will continue to poke around and post updates here.

**Comment by lengstrom** [comment]
I think your goal is pretty underspecified right now. I'm not sure what "when alpha = 0 the style transfer isn't applied" means.

**Comment by onyedikilo** [comment]
He probably means that he has an RGBA image with an alpha channel as the transparency and he wants the style to apply only to the pixels where there is no transparency (opaque). Like an alpha mask.
