### ISSUE TITLE
How do I swt content-weight, style-weight, tv-weight?

### ISSUE THREAD

**Issue by chumhoiyan** [lengstrom/fast-style-transfer#73]
I am new to deep learning.. I wonder how to set content-weight, style-weight and tv-weight if I want the output to be more abstract﻿

**Comment by stevedipaola** [comment]
same feature request here - is there any variability available at the model creation or better the evaluation time at all - can we expose some parameters inherent in the system that can be used to better tailor the results.

**Comment by lengstrom** [comment]
read the docs

**Comment by shartoo** [comment]
change `biases_initializer=tf.zeros_initializer()`  into `biases_initializer=tf.zeros_initializer` works for me.
