### ISSUE TITLE
Multiple GPU support

### ISSUE THREAD

**Issue by FaisalAbid** [lengstrom/fast-style-transfer#80]
I'm running this on a google cloud machine with 8 gpus. I can see Tensorflow detect all the gpus, however training takes just as long as it would on a 1 gpu machine.

Is there something specific that needs to be done to make this utilize all gpus?

**Comment by ShenZhouHong** [comment]
I have a similar question as well. Does this codebase take advantage of multiple GPUs, or is it suitable for a single GPU only?

**Comment by lengstrom** [comment]
Single GPU only for now, PRs welcome.

**Comment by marcsyp** [comment]
Any update on this?  Would love to be able to run this on multiple GPUs...

**Comment by TonyMou** [comment]
How to use multiple GPUs for training? Any update on this?
