### ISSUE TITLE
Running Out of Memmory

### ISSUE THREAD

**Issue by yurikleb** [lengstrom/fast-style-transfer#82]
Hi I'm bit new to using tensor flow,
But both evaluate.py and transform_video.py work really well using the sample files and models provided.
But it seems like I'm running out of memory when attempting to train a new model. 

I'm using GeForce GTX 750 Ti
when running style.py, TensorFlow finds the GPU and prints the following:

`name: GeForce GTX 750 Ti
major: 5 minor: 0 memoryClockRate (GHz) 1.0845
pciBusID 0000:01:00.0
Total memory: 1.95GiB
Free memory: 1.63GiB`

Then it starts running, but after a few seconds crashes, due to what seems to be memory allocation problem (please see attached screenshots).

![screenshot from 2017-06-14 23-34-03](https://user-images.githubusercontent.com/12280733/27137891-0e315dc4-515a-11e7-911f-f6375db0192c.png)
![screenshot from 2017-06-14 23-34-18](https://user-images.githubusercontent.com/12280733/27137892-0e3fb40a-515a-11e7-86ed-39987bf0bcc7.png)
![screenshot from 2017-06-14 23-34-26](https://user-images.githubusercontent.com/12280733/27137890-0e30ffdc-515a-11e7-837a-e9bc115b710a.png)

Are there any preferable flag settings when running style.py to avoid memory overflow?

thanks in advance!

**Comment by yihongXU** [comment]
reduce your image size before stylization.

**Comment by maximr** [comment]
@yihongXU This is not really an option for some scenarios. There should be a way to split the tensor into multiple batches when processing it. I'm not able to run the evaluation on a gpu for anything that goes beyond the standard size. Run out of memory on a GTX 980 - which might not be the best card but also not the worst.

**Comment by yurikleb** [comment]
Just tried quite small image 300x300px and but still get a `ResourceExhaustedError`
I know my GPU is not the best but I don't mind waiting longer as long as works. 
Any other options to make it work?

Many thanks!

**Comment by maximr** [comment]
@yurikleb Try using CPU computation - this should work in every case. I think you can pass it as a parameter - or just try to change the line in evaluate.py

**Comment by yurikleb** [comment]
evaluate.py and transform_video.py work well, trouble starts when I try to train a new style. CPU computation works but is quite slow :(

**Comment by maximr** [comment]
@yurikleb did you try tweaking this settings:

```
config.gpu_options.allow_growth = True
config.gpu_options.per_process_gpu_memory_fraction = 0.4 #or other value
config.gpu_options.allocator_type = 'BFC'
```

if non of that works - you might consider using an AWS GPU instance, upgrade your GPU or change the first CNN layer for training or try to find a way to pipe stuff into multiple batches - see Cifar example. How ever: You might be better of using a different library at all (-:

**Comment by yurikleb** [comment]
Cool! will try tweaking the settings and report!

**Comment by Jashmi** [comment]
@yurikleb Did you modify or do any pre-processing on new videos when you tried to train a new model or style?

**Comment by yurikleb** [comment]
nope, didn't do any pre-processing.
Sorry, didn't have time to make further testing yet.
