### ISSUE TITLE
problem in .ckpt file

### ISSUE THREAD

**Issue by tuteming** [lengstrom/fast-style-transfer#89]
hi! I run "python evaluate.py --checkpoint models/la_muse.ckpt --in-path in --out-path out --allow-different-dimensions" this ok. here la_muse.ckpt size is 20M.
when run "python style.py --style style/la_muse.jpg --checkpoint-dir checkpoint "
which dir/checkpoint create 3 file, total size ~140M.
also run "python evaluate.py --checkpoint checkpoint --in-path in --out-path out --allow-different-dimensions". that also is ok.
my problem is how to convert 3 file to single ckpt file.
or how to set in  style.py for create single ckpt file.
thanks.

**Comment by jeroenherczeg** [comment]
I have the same problem. I have now followed https://github.com/lengstrom/fast-style-transfer/issues/78#issuecomment-302307215 and I am running the training again. Hope this solves the problem.

**Comment by jeroenherczeg** [comment]
It did solve the problem, I now have 3 files, with one being a .ckpt. which works!

**Comment by tuteming** [comment]
thanks. I will try it.

**Comment by spot92** [comment]
Was there ever a way determined to turn 3 different files into one .ckpt file?
