### ISSUE TITLE
OOM on Titan X Pascal

### ISSUE THREAD

**Issue by spiantino** [lengstrom/fast-style-transfer#9]
Any tips for making this fit on 12G? I get the following oom using evaluate.py:

```
I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 9.18GiB
I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                 11990125773
InUse:                  9853348352
MaxInUse:              11713353216
NumAllocs:                     456
MaxAllocSize:           4294967296

W tensorflow/core/common_runtime/bfc_allocator.cc:274] *_********************************xxxx**********************xxxxxxxxxxxxxx***********_______________
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 2.34GiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:968] Resource exhausted: OOM when allocating tensor with shape[1,32,3728,5264]
Traceback (most recent call last):
  File "evaluate.py", line 125, in <module>
    main()
  File "evaluate.py", line 122, in main
    batch_size=opts.batch_size)
  File "evaluate.py", line 59, in ffwd
    _preds = sess.run(preds, feed_dict={img_placeholder:X})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shape[1,32,3728,5264]
         [[Node: conv2d_transpose_1 = Conv2DBackpropInput[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](pack_1, Variable_42/read, Relu_8)]]
```

**Comment by lengstrom** [comment]
I had this issue earlier, I'll look in a few hours! It should work for you
on 12gb.

**Comment by lengstrom** [comment]
Could you send me enough details to reproduce this on my machine? I'll need your checkpoint file and your input image.

**Comment by spiantino** [comment]
sure - I'm using your wave.ckpt file and a random image from my iphone. I've tried it with various images of different dimensions and the result is the same, so I don't think it's dependent on that.

here's the command line: `python evaluate.py --checkpoint ./wave.ckpt --in-path input/ --out-path output/`

**Comment by spiantino** [comment]
here's a full log:

> serkan@titan:~/deeplearning/fast-style-transfer$ python evaluate.py --checkpoint ./wave.ckpt --in-path input/ --out-path output/ >> out.txt
> I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so.8.0 locally
> I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so.5 locally
> I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so.8.0 locally
> I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
> I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so.8.0 locally
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties: 
> name: TITAN X (Pascal)
> major: 6 minor: 1 memoryClockRate (GHz) 1.531
> pciBusID 0000:02:00.0
> Total memory: 11.90GiB
> Free memory: 11.75GiB
> W tensorflow/stream_executor/cuda/cuda_driver.cc:572] creating context when one is currently active; existing: 0x2d15910
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 1 with properties: 
> name: TITAN X (Pascal)
> major: 6 minor: 1 memoryClockRate (GHz) 1.531
> pciBusID 0000:01:00.0
> Total memory: 11.90GiB
> Free memory: 11.58GiB
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0 1 
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y Y 
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 1:   Y Y 
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:02:00.0)
> I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:1) -> (device: 1, name: TITAN X (Pascal), pci bus id: 0000:01:00.0)
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (256):       Total Chunks: 1, Chunks in use: 0 256B allocated for chunks. 128
> B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (512):       Total Chunks: 1, Chunks in use: 0 512B allocated for chunks. 128
> B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (1024):      Total Chunks: 1, Chunks in use: 0 1.0KiB allocated for chunks. 1
> 28B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (2048):      Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B cl
> ient-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (4096):      Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B cl
> ient-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (8192):      Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B cl
> ient-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (16384):     Total Chunks: 1, Chunks in use: 0 30.0KiB allocated for chunks. 
> 512B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (32768):     Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B cl
> ient-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (65536):     Total Chunks: 2, Chunks in use: 0 143.0KiB allocated for chunks.
>  102.4KiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (131072):    Total Chunks: 1, Chunks in use: 0 212.0KiB allocated for chunks.
>  0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (262144):    Total Chunks: 1, Chunks in use: 0 288.2KiB allocated for chunks.
>  256B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (524288):    Total Chunks: 2, Chunks in use: 0 1.19MiB allocated for chunks. 
> 1.12MiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (1048576):   Total Chunks: 1, Chunks in use: 0 1.69MiB allocated for chunks. 
> 783.9KiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (2097152):   Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B cl
> ient-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (4194304):   Total Chunks: 1, Chunks in use: 0 4.62MiB allocated for chunks. 
> 12B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (8388608):   Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B cl
> ient-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (16777216):  Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B cl
> ient-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (33554432):  Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B cl
> ient-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (67108864):  Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B cl
> ient-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (134217728):         Total Chunks: 0, Chunks in use: 0 0B allocated for chunk
> s. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (268435456):         Total Chunks: 1, Chunks in use: 0 512.00MiB allocated fo
> r chunks. 274.66MiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
> I tensorflow/core/common_runtime/bfc_allocator.cc:660] Bin for 2.86GiB was 256.00MiB, Chunk State: 
> I tensorflow/core/common_runtime/bfc_allocator.cc:666]   Size: 512.00MiB | Requested Size: 274.66MiB | in_use: 0
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041ac00000 of size 1280
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041ac00500 of size 1047296
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b400000 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b400100 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b400200 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b400300 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b400400 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b400500 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b400600 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b400800 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b400a00 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b400c00 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b412800 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b412a00 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b412c00 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b412d00 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b45b000 of size 295424
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b4a3200 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b4a3300 of size 73728
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b4b5300 of size 589824
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b545300 of size 294912
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b58d300 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b58d400 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b58d500 of size 31232
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b594f00 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b595000 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b595200 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b595300 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b595400 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b595600 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b595800 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b595a00 of size 31232
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5af600 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5af800 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5af900 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5afa00 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5afc00 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5afe00 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5b0000 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5b0200 of size 768
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5b0500 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5b0700 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5b0b00 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5b1100 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5b1200 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5b1400 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5b8e00 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b5b9000 of size 73728
> I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1041b400e00 of size 72192
> I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1041b412f00 of size 295168
> I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1041b59d400 of size 74240
> I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1041b5b0100 of size 256
> I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1041b5b0900 of size 512
> I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1041b5b0d00 of size 1024
> I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1041b5b1600 of size 30720
> I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1041b5cb000 of size 217088
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041b9b0000 of size 589824
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041ba40000 of size 589824
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041bad0000 of size 589824
> I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1041b800000 of size 1769472
> I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1041bb60000 of size 655360
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041c090000 of size 589824
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041c120000 of size 589824
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041c1b0000 of size 589824
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041c240000 of size 589824
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1041c2d0000 of size 589824
> I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1041c000000 of size 589824
> I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1041c360000 of size 4849664
> I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x1041cc00000 of size 536870912
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1043cc00000 of size 4294967296
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1053cc00000 of size 4294967296
> I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x1063d000000 of size 2847591424
> I tensorflow/core/common_runtime/bfc_allocator.cc:693]      Summary of in-use Chunks by size: 
> I tensorflow/core/common_runtime/bfc_allocator.cc:696] 17 Chunks of size 256 totalling 4.2KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:696] 21 Chunks of size 512 totalling 10.5KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 768 totalling 768B
> I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1280 totalling 1.2KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 31232 totalling 61.0KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 73728 totalling 144.0KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 294912 totalling 288.0KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 295424 totalling 288.5KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:696] 9 Chunks of size 589824 totalling 5.06MiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1047296 totalling 1022.8KiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 2847591424 totalling 2.65GiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 4294967296 totalling 8.00GiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 10.66GiB
> I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
> Limit:                 11990125773
> InUse:                 11444699136
> MaxInUse:              11444699136
> NumAllocs:                     131
> MaxAllocSize:           4294967296
> 
> W tensorflow/core/common_runtime/bfc_allocator.cc:274] *___***************************xxxxxxxxx***************************xxxxxxxxx*****
> *********xxxxxxxxxx
> W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 2.86GiB.  See logs for memory state.
> W tensorflow/core/framework/op_kernel.cc:968] Resource exhausted: OOM when allocating tensor with shape[1,32,4001,6001]
> Traceback (most recent call last):
>   File "evaluate.py", line 125, in <module>
>     main()
>   File "evaluate.py", line 122, in main
>     batch_size=opts.batch_size)
>   File "evaluate.py", line 59, in ffwd
>     _preds = sess.run(preds, feed_dict={img_placeholder:X})
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
>     feed_dict_string, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
>     target_list, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors.ResourceExhaustedError: OOM when allocating tensor with shape[1,32,4001,6001]
>          [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device=
> "/job:localhost/replica:0/task:0/gpu:0"](Relu, Variable_3/read)]]
>          [[Node: add_37/_99 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:loca
> lhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_51_add_37", tensor_type=DT_FLOAT, _device="/job:localhost/re
> plica:0/task:0/cpu:0"]()]]
> 
> Caused by op u'Conv2D_1', defined at:
>   File "evaluate.py", line 125, in <module>
>     main()
>   File "evaluate.py", line 122, in main
>     batch_size=opts.batch_size)
>   File "evaluate.py", line 34, in ffwd
>     preds = transform.net(img_placeholder)
>   File "src/transform.py", line 7, in net
>     conv2 = _conv_layer(conv1, 64, 3, 2)
>   File "src/transform.py", line 23, in _conv_layer
>     net = tf.nn.conv2d(net, weights_init, strides_shape, padding='SAME')
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 394, in conv2d
>     data_format=data_format, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
>     op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2388, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1300, in __init__
>     self._traceback = _extract_stack()
> 
> ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[1,32,4001,6001]
>          [[Node: Conv2D_1 = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device=
> "/job:localhost/replica:0/task:0/gpu:0"](Relu, Variable_3/read)]]
>          [[Node: add_37/_99 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:loca
> lhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_51_add_37", tensor_type=DT_FLOAT, _device="/job:localhost/re
> plica:0/task:0/cpu:0"]()]]

**Comment by spiantino** [comment]
Same result when I use CUDA_VISIBLE_DEVICES to only show TF one of the 2 Titans

**Comment by spiantino** [comment]
Training seems to work fine, has been running for 10m without issue (and uses all 12G on both cards).

**Comment by spiantino** [comment]
Success! With a smaller image it worked after all.

**Comment by lengstrom** [comment]
Great! Should I close this issue?

**Comment by spiantino** [comment]
Yep, I think we're good to go
