### ISSUE TITLE
paths_out and data_in empty for video style transfer

### ISSUE THREAD

**Issue by cl445** [lengstrom/fast-style-transfer#93]
Hi!
Great model, thanks for implementing this and making it available. 
While the style transfer for images worked very well for me, I always get the same error when trying to use video.
I tried e.g. 
python transform_video.py --in-path ~/fast-style-transfer/examples/content/fox.mp4 --checkpoint ~/PycharmProjects/fast-style-transfer/udnie.ckpt --out-path ~/fast-style-transfer/examples/myResults/ --batch-size 4
and always get this error:
"/bin/sh: 1: ffmpeg: not found
Traceback (most recent call last):
  File "transform_video.py", line 90, in <module>
    main()
  File "transform_video.py", line 73, in main
    batch_size=opts.batch_size)
  File "/home/demden/PycharmProjects/fast-style-transfer/evaluate.py", line 127, in ffwd
    assert len(paths_out) > 0
AssertionError"
Diving into the code, it seems as if the paths_out and data_in are empty no matter what I do.
Could you let me know what I'm doing wrong?
Thanks in advance.
Cheers,
Claas

**Comment by Tetsujinfr** [comment]
It tells you it cannot find ffmpeg (the coe is using ffmpeg to extract png frame out of the input video), so you likely do not have ffmpeg installed.
If you are under linux type in "sudo apt-get install ffmpeg" and press enter...
