### ISSUE TITLE
How to execute this

### ISSUE THREAD

**Issue by abc1714** [lengstrom/fast-style-transfer#97]
Sorry, i may be the dumbest person here. and let me ask the dumbest question. i need this project for my bachelors submission and i've confirmed with my professors that if i can use something available on github. I am running a windows machine with i5 7300Q and gtx1050. Now the question is, would any of you please help me in understanding the code and executing on my machine. would be highly appreciated

**Comment by lengstrom** [comment]
My consulting fees are $1000/hr, please let me know if you are interested :)
